# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/abdelfetah-dev/Desktop/JsonCpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/abdelfetah-dev/Desktop/JsonCpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abdelfetah-dev/Desktop/JsonCpp/CMakeFiles /home/abdelfetah-dev/Desktop/JsonCpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abdelfetah-dev/Desktop/JsonCpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JsonCpp

# Build rule for target.
JsonCpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JsonCpp
.PHONY : JsonCpp

# fast build rule for target.
JsonCpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/build
.PHONY : JsonCpp/fast

data_structures/ByteBuffer.o: data_structures/ByteBuffer.cpp.o
.PHONY : data_structures/ByteBuffer.o

# target to build an object file
data_structures/ByteBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/ByteBuffer.cpp.o
.PHONY : data_structures/ByteBuffer.cpp.o

data_structures/ByteBuffer.i: data_structures/ByteBuffer.cpp.i
.PHONY : data_structures/ByteBuffer.i

# target to preprocess a source file
data_structures/ByteBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/ByteBuffer.cpp.i
.PHONY : data_structures/ByteBuffer.cpp.i

data_structures/ByteBuffer.s: data_structures/ByteBuffer.cpp.s
.PHONY : data_structures/ByteBuffer.s

# target to generate assembly for a file
data_structures/ByteBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/ByteBuffer.cpp.s
.PHONY : data_structures/ByteBuffer.cpp.s

data_structures/GenericParser.o: data_structures/GenericParser.cpp.o
.PHONY : data_structures/GenericParser.o

# target to build an object file
data_structures/GenericParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/GenericParser.cpp.o
.PHONY : data_structures/GenericParser.cpp.o

data_structures/GenericParser.i: data_structures/GenericParser.cpp.i
.PHONY : data_structures/GenericParser.i

# target to preprocess a source file
data_structures/GenericParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/GenericParser.cpp.i
.PHONY : data_structures/GenericParser.cpp.i

data_structures/GenericParser.s: data_structures/GenericParser.cpp.s
.PHONY : data_structures/GenericParser.s

# target to generate assembly for a file
data_structures/GenericParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/GenericParser.cpp.s
.PHONY : data_structures/GenericParser.cpp.s

data_structures/Json.o: data_structures/Json.cpp.o
.PHONY : data_structures/Json.o

# target to build an object file
data_structures/Json.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/Json.cpp.o
.PHONY : data_structures/Json.cpp.o

data_structures/Json.i: data_structures/Json.cpp.i
.PHONY : data_structures/Json.i

# target to preprocess a source file
data_structures/Json.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/Json.cpp.i
.PHONY : data_structures/Json.cpp.i

data_structures/Json.s: data_structures/Json.cpp.s
.PHONY : data_structures/Json.s

# target to generate assembly for a file
data_structures/Json.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/Json.cpp.s
.PHONY : data_structures/Json.cpp.s

data_structures/String.o: data_structures/String.cpp.o
.PHONY : data_structures/String.o

# target to build an object file
data_structures/String.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/String.cpp.o
.PHONY : data_structures/String.cpp.o

data_structures/String.i: data_structures/String.cpp.i
.PHONY : data_structures/String.i

# target to preprocess a source file
data_structures/String.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/String.cpp.i
.PHONY : data_structures/String.cpp.i

data_structures/String.s: data_structures/String.cpp.s
.PHONY : data_structures/String.s

# target to generate assembly for a file
data_structures/String.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/String.cpp.s
.PHONY : data_structures/String.cpp.s

data_structures/StringView.o: data_structures/StringView.cpp.o
.PHONY : data_structures/StringView.o

# target to build an object file
data_structures/StringView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/StringView.cpp.o
.PHONY : data_structures/StringView.cpp.o

data_structures/StringView.i: data_structures/StringView.cpp.i
.PHONY : data_structures/StringView.i

# target to preprocess a source file
data_structures/StringView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/StringView.cpp.i
.PHONY : data_structures/StringView.cpp.i

data_structures/StringView.s: data_structures/StringView.cpp.s
.PHONY : data_structures/StringView.s

# target to generate assembly for a file
data_structures/StringView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/data_structures/StringView.cpp.s
.PHONY : data_structures/StringView.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JsonCpp.dir/build.make CMakeFiles/JsonCpp.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... JsonCpp"
	@echo "... data_structures/ByteBuffer.o"
	@echo "... data_structures/ByteBuffer.i"
	@echo "... data_structures/ByteBuffer.s"
	@echo "... data_structures/GenericParser.o"
	@echo "... data_structures/GenericParser.i"
	@echo "... data_structures/GenericParser.s"
	@echo "... data_structures/Json.o"
	@echo "... data_structures/Json.i"
	@echo "... data_structures/Json.s"
	@echo "... data_structures/String.o"
	@echo "... data_structures/String.i"
	@echo "... data_structures/String.s"
	@echo "... data_structures/StringView.o"
	@echo "... data_structures/StringView.i"
	@echo "... data_structures/StringView.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

